/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAnchor: typeof import('ant-design-vue/es')['Anchor']
    AApp: typeof import('ant-design-vue/es')['App']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AntdLanguage: typeof import('./../src/components/icons/antd-language.vue')['default']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    CarbonMoon: typeof import('./../src/components/icons/carbon-moon.vue')['default']
    CarbonSun: typeof import('./../src/components/icons/carbon-sun.vue')['default']
    CodeBoxLink: typeof import('./../src/components/icons/code-box-link.vue')['default']
    CodePen: typeof import('./../src/components/icons/code-pen.vue')['default']
    CodeSandbox: typeof import('./../src/components/icons/code-sandbox.vue')['default']
    DemoBlock: typeof import('./../src/components/demo-block/index.vue')['default']
    EdIt: typeof import('./../src/components/icons/edIt.vue')['default']
    Expand: typeof import('./../src/components/icons/expand.vue')['default']
    FileCopy: typeof import('./../src/components/icons/file-copy.vue')['default']
    FileSuccess: typeof import('./../src/components/icons/file-success.vue')['default']
    Group: typeof import('./../src/components/demo-block/group.vue')['default']
    Icon: typeof import('./../src/components/demo-block/icon.vue')['default']
    IframeBlock: typeof import('./../src/components/demo-block/iframe-block.vue')['default']
    ProProvider: typeof import('./../src/components/pro-provider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stackblitz: typeof import('./../src/components/icons/stackblitz.vue')['default']
    TokenProvider: typeof import('./../src/components/token-provider.vue')['default']
    UnExpand: typeof import('./../src/components/icons/un-expand.vue')['default']
  }
}
