/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('ant-design-vue/es')['App']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AntdLanguage: typeof import('./../src/components/icons/antd-language.vue')['default']
    Antdv: typeof import('../src/components/pro-provider.vue')['default']
    APopover: typeof import('ant-design-vue/es')['Popover']
    CarbonMoon: typeof import('./../src/components/icons/carbon-moon.vue')['default']
    CarbonSun: typeof import('./../src/components/icons/carbon-sun.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    ProProvider: typeof import('./../src/components/pro-provider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TokenProvider: typeof import('./../src/components/token-provider.vue')['default']
  }
}
