/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/backend/': RouteRecordInfo<'/backend/', '/backend', Record<never, never>, Record<never, never>>,
    '/backend/setup/build': RouteRecordInfo<'/backend/setup/build', '/backend/setup/build', Record<never, never>, Record<never, never>>,
    '/components/': RouteRecordInfo<'/components/', '/components', Record<never, never>, Record<never, never>>,
    '/components/pro-table/': RouteRecordInfo<'/components/pro-table/', '/components/pro-table', Record<never, never>, Record<never, never>>,
    '/components/pro-table/basic': RouteRecordInfo<'/components/pro-table/basic', '/components/pro-table/basic', Record<never, never>, Record<never, never>>,
    '/components/pro-table/demos/basic': RouteRecordInfo<'/components/pro-table/demos/basic', '/components/pro-table/demos/basic', Record<never, never>, Record<never, never>>,
    '/components/schema-form/': RouteRecordInfo<'/components/schema-form/', '/components/schema-form', Record<never, never>, Record<never, never>>,
    '/components/schema-form/basic': RouteRecordInfo<'/components/schema-form/basic', '/components/schema-form/basic', Record<never, never>, Record<never, never>>,
    '/components/schema-form/demos/basic': RouteRecordInfo<'/components/schema-form/demos/basic', '/components/schema-form/demos/basic', Record<never, never>, Record<never, never>>,
    '/components/schema-form/demos/depend': RouteRecordInfo<'/components/schema-form/demos/depend', '/components/schema-form/demos/depend', Record<never, never>, Record<never, never>>,
    '/components/schema-form/demos/depend-event': RouteRecordInfo<'/components/schema-form/demos/depend-event', '/components/schema-form/demos/depend-event', Record<never, never>, Record<never, never>>,
    '/components/schema-form/demos/request': RouteRecordInfo<'/components/schema-form/demos/request', '/components/schema-form/demos/request', Record<never, never>, Record<never, never>>,
    '/components/schema-form/depend': RouteRecordInfo<'/components/schema-form/depend', '/components/schema-form/depend', Record<never, never>, Record<never, never>>,
    '/components/schema-form/request': RouteRecordInfo<'/components/schema-form/request', '/components/schema-form/request', Record<never, never>, Record<never, never>>,
    '/guide/': RouteRecordInfo<'/guide/', '/guide', Record<never, never>, Record<never, never>>,
    '/guide/demos/basic': RouteRecordInfo<'/guide/demos/basic', '/guide/demos/basic', Record<never, never>, Record<never, never>>,
    '/guide/quickstart': RouteRecordInfo<'/guide/quickstart', '/guide/quickstart', Record<never, never>, Record<never, never>>,
    '/guide/test': RouteRecordInfo<'/guide/test', '/guide/test', Record<never, never>, Record<never, never>>,
  }
}
